"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";

//import { Authenticator } from "@aws-amplify/ui-react";
//import "@aws-amplify/ui-react/styles.css";


const inter = Inter({ subsets: ["latin"] });
//Auth: {
//  Cognito: {
//    userPoolId: "us-east-1_cwR5jLfKp",
//    userPoolClientId: "t5tjiuuh18h4g6au49qo4lnds",
//    identityPoolId: "us-east-1:788769ff-e3df-41d8-910e-7316d3cf6bfc",
//    loginWith: {
//      username: true
//    }
//  }
//}
//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next apped",
//};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  );
}

//Authenticator
//hideSignUp={true}
//loginMechanisms={['username']}
//>
//{children}
//</Authenticator>