name: CI/CD workflow

on: 
  push:
    branches:
      - main
      - ampliyf-development
      - upload-POST-api

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install dependencies
        run: npm install

      - name: Runs end-to-end tests
        run: |
          output=$(npm test __test__/**.test.ts --coverage)

          coverage_line=$(echo "$output" | grep -E '^All files\s+\|\s+[0-9.]+' | grep -oE '[0-9.]+' | tail -n 1)

          echo "Test Coverage: $coverage_line"

          if [ "$coverage_line" != "100" ]; then
          check=$(echo "$coverage_line" | grep -oE '[0-9]{2}.' | grep -oE '[0-9]{2}')
          if [ "$check" -lt 70 ];
          then
          echo "Test Coverage is below 70%"
          exit 1
          fi
          fi

          lint_output=$(npm run lint)
          echo "$lint_output"
          